---
gunicorn_user: gunicorn
nginx_user: nginx

# The messy syntax is required so we can dynamically set the user's names.
users: "{
    '{{ gunicorn_user }}': {},
    '{{ nginx_user }}': { 'create_home': false },
  }"


python_app_name: km-api
python_app_repo: https://github.com/knowmetools/km-api
python_app_version: develop
python_app_user: "{{ gunicorn_user }}"
python_app_source_update_handlers:
  - gunicorn reload


django_project_root: "{{ python_app_root }}/km_api"
django_user: "{{ gunicorn_user }}"
django_venv: "{{ python_app_venv }}"

django_env:
  DJANGO_ALLOWED_HOSTS: "{{ inventory_hostname }}"
  DJANGO_AWS_REGION: "{{ aws_region }}"

  DJANGO_DB_HOST: "{{ db_host }}"
  DJANGO_DB_NAME: "{{ db_name }}"
  DJANGO_DB_PASSWORD: "{{ db_password }}"
  DJANGO_DB_PORT: "{{ db_port }}"
  DJANGO_DB_USER: "{{ db_user }}"

  DJANGO_HTTPS: True

  DJANGO_EMAIL_VERIFICATION_URL: https://{{ webapp_url }}/verify-email/{key}
  DJANGO_PASSWORD_RESET_URL: https://{{ webapp_url }}/reset-password/{key}

  DJANGO_S3_BUCKET: "{{ static_files_bucket }}"
  DJANGO_S3_STORAGE: True

  DJANGO_SECRET_KEY: "{{ django_secret_key }}"

  DJANGO_SES_ENABLED: True


app_config_dir: /etc/km-api
app_config_env: "{{ django_env }}"
app_config_env_file_handlers:
  - gunicorn restart
app_config_user: "{{ gunicorn_user }}"


gunicorn_application: km_api.wsgi:application
gunicorn_env_file: "{{ app_config_env_file }}"
gunicorn_venv: "{{ python_app_venv }}"
gunicorn_working_directory: "{{ django_project_root }}"


letsencrypt_domain: "{{ inventory_hostname }}"
letsencrypt_email: tech@knowmetools.com


nginx_certificate: "{{ letsencrypt_cert_dir }}/fullchain.pem"
nginx_certificate_key: "{{ letsencrypt_cert_dir }}/privkey.pem"
nginx_dhparam: "{{ letsencrypt_dhparam }}"
nginx_proxy_socket: "{{ gunicorn_socket }}"
