---
- name: Install Gunicorn
  become: true
  become_user: "{{ gunicorn_user }}"
  pip:
    name: gunicorn
    state: latest
    virtualenv: "{{ gunicorn_venv }}"
  notify: gunicorn reload

- name: Create main Gunicorn service
  become: true
  template:
    dest: "{{ gunicorn_service_file }}"
    mode: 0644
    src: gunicorn.service.j2
  notify:
    - daemon reload
    - gunicorn reload

- name: Create socket for Gunicorn service
  become: true
  template:
    dest: "{{ gunicorn_service_socket }}"
    mode: 0644
    src: gunicorn.socket.j2
  notify:
    - daemon reload
    - gunicorn socket restart
    - gunicorn reload

- name: Create tempfiles configuration for Gunicorn service
  become: true
  template:
    dest: "{{ gunicorn_service_tempfile }}"
    mode: 0644
    src: gunicorn.conf.j2
  notify:
    - daemon reload
    - gunicorn reload

- name: Enable Gunicorn socket
  become: true
  systemd:
    enabled: true
    name: gunicorn.socket
    state: started
