---
- name: Install NGINX
  become: true
  apt:
    name: nginx
    state: latest
  notify: reload nginx

- name: Upload NGINX configuration
  become: true
  template:
    dest: /etc/nginx/nginx.conf
    mode: 0644
    src: nginx.conf.j2
  notify: restart nginx

- name: Enable NGINX
  become: true
  systemd:
    enabled: true
    name: nginx
    state: started
