---
- hosts: all

  become_user: root
  remote_user: ubuntu

  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Update apt repositories
      become: true
      apt:
        update_cache: true

  roles:
    - users
    - app-config
    - python-app
    - django
    - gunicorn
